kabi_chuckles/creation/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
	# when including urls from another app, leave the ^ and $ in the main urls.py, such as --> url(r'', include('creation.urls')),
	# and in the app's urls.py include them both such as, r'^$' or r'^snaps/$'
    url(r'^$', 'creation.views.home', name='home'),
    url(r'^blog/$', 'creation.views.blog', name='blog'),
    url(r'^blog/(?P<blog_pk>\d+)/$', 'creation.views.blog_detail', name='blog_detail'),
    url(r'^illustration/$', 'creation.views.illustration', name='illustration'),
    url(r'^illustration/(?P<illustration_pk>\d+)/$', 'creation.views.illustration_detail', name='illustration_detail'),
    url(r'^inspiration/$', 'creation.views.inspiration', name='inspiration'),
    url(r'^inspiration/(?P<inspiration_pk>\d+)/$', 'creation.views.inspiration_detail', name='inspiration_detail'),
    url(r'^fashion/$', 'creation.views.fashion', name='fashion'),
    url(r'^fashion/(?P<fashion_pk>\d+)/$', 'creation.views.fashion_detail', name='fashion_detail'),
    url(r'^snaps/$', 'creation.views.snaps', name='snaps'),
    url(r'^about/$', 'creation.views.about', name='about'),
)

kabi_chuckles/kabi_chuckles/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	# when including urls from another app, leave the ^ and $ in the main urls.py, such as --> url(r'', include('creation.urls')),
	# and in the app's urls.py include them both, such as --> url(r'^$', 'creation.views.home', name='home'), OR url(r'^snaps/$', 'creation.views.snaps', name='snaps'),
    url(r'', include('creation.urls')),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

kabi_chuckles/creation/models.py
from django.db import models
from django.utils import timezone
from time import time
from datetime import date
import re
from bs4 import BeautifulSoup


# TYPES = (
# 	('BL', 'BLOG'),
# 	('IL', 'ILLUSTRATIONS'),
# 	('IN', 'INSPIRATION'),
# 	('FA', 'FASHION'),
# 	('SN', 'SNAPS'),
# 	)

# class Content(models.Model):
# 	title = models.CharField(max_length=300, blank=True, null=True)
# 	description = models.TextField(blank=True, null=True)
# 	# image = models.ImageField(upload_to=get_upload_file_name, blank=True, null=True, default='')
# 	pubdate = models.DateTimeField(default=timezone.now)
# 	update = models.DateTimeField(default=timezone.now)
# 	# of_type = models.CharField(max_length=2,choices=TYPES)
# 	for_home = models.BooleanField(default=False)

# 	# publish = models.booleanfield(default=True)

# 	def __unicode__(self):
# 		return ("%s : %s") % (self.of_type, self.title)

def get_upload_file_name(instance, filename):
	return "uploaded_files/%s_%s" %(str(time()).replace('.','_'), filename)


class Home(models.Model):
	image1 = models.ImageField(upload_to=get_upload_file_name)
	image2 = models.ImageField(upload_to=get_upload_file_name)
	image3 = models.ImageField(upload_to=get_upload_file_name)
	image4 = models.ImageField(upload_to=get_upload_file_name)
	image5 = models.ImageField(upload_to=get_upload_file_name)
	image6 = models.ImageField(upload_to=get_upload_file_name)
	pubdate = models.DateTimeField(default=timezone.now)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return unicode(self.pubdate)


class Blog(models.Model):
	title = models.CharField(max_length=150, blank=True)
	description = models.TextField()
	first_image = models.CharField(max_length=200, blank=True)
	default_first_image_size = models.BooleanField(default=False)
	pubdate = models.DateTimeField(default=timezone.now)
	publish = models.BooleanField(default=False)


	def save(self, *args, **kwargs):
		# This regex will grab your first img url
		# Note that you have to use double quotes for the src attribute
		img = re.search('src="([^"]+)"'[4:], self.description)
		self.first_image = img.group().strip('"')
		super(Blog, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return ("%s : %s") % (self.pubdate, self.title)


class Illustration(models.Model):
	title = models.CharField(max_length=150, blank=True)
	description = models.TextField()
	first_image = models.TextField(blank=True)
	default_first_image_size = models.BooleanField(default=False)
	pubdate = models.DateTimeField(default=timezone.now)
	publish = models.BooleanField(default=True)

	def save(self, *args, **kwargs):
	    soup = BeautifulSoup(self.description)
	    self.first_image = soup.find('img')['src']
	    super(Illustration, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return ("%s : %s") % (self.pubdate, self.title)


class Inspiration(models.Model):
	title = models.CharField(max_length=150, blank=True)
	description = models.TextField()
	first_image = models.TextField(blank=True)
	pubdate = models.DateTimeField(default=timezone.now)
	publish = models.BooleanField(default=True)

	def save(self, *args, **kwargs):
		# This regex will grab your first img url
		# Note that you have to use double quotes for the src attribute
		img = re.search('src="([^"]+)"'[4:], self.description)
		self.first_image = img.group().strip('"')
		super(Inspiration, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return ("%s : %s") % (self.pubdate, self.title)

class Fashion(models.Model):
	title = models.CharField(max_length=150, blank=True)
	description = models.TextField()
	first_image = models.TextField(blank=True)
	pubdate = models.DateTimeField(default=timezone.now)
	publish = models.BooleanField(default=True)

	def save(self, *args, **kwargs):
		# This regex will grab your first img url
		# Note that you have to use double quotes for the src attribute
		img = re.search('src="([^"]+)"'[4:], self.description)
		self.first_image = img.group().strip('"')
		super(Fashion, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return ("%s : %s") % (self.pubdate, self.title)

class SnapGroup(models.Model):
	name = models.CharField(max_length=150, blank=True, null=True)
	date = models.DateField(default=date.today)

	def __unicode__(self):
		if self.name:
			return ("%s : %s") % (self.date, self.name)
		else:
			return unicode(self.date)

class Snap(models.Model):
	date = models.ForeignKey(SnapGroup)
	image = models.ImageField(upload_to=get_upload_file_name)
	caption = models.CharField(max_length=150, blank=True, null=True)

	class Meta:
		ordering = ['-date']

	def __unicode__(self):
		return ("%s : %s") % (self.date, self.caption)

class About(models.Model):
	description = models.TextField()
	pubdate = models.DateTimeField(default=timezone.now)

	class Meta:
		ordering = ['-pubdate']

	def __unicode__(self):
		return unicode(self.pubdate)

kabi_chuckles/templates/about.html
{% extends "base.html" %}

{% block main_content %}

  <div class="container">
      <hr>
      <div id="about">
          <div class="row">
          	{% if about %}
            	{{ about.description | safe }}
          	{% else %}
          		<p>No about</p>
          	{% endif %}
          </div>
      </div>
  </div>

{% endblock %}

kabi_chuckles/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Bootstrap</title>

         <!-- Bootstrap css Starts -->
        <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap.min.css">
        
        <!-- Custom css starts -->
        <link rel="stylesheet" href="{{STATIC_URL}}css/custom.css">

        <!-- Parallax starts -->
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/parallax.css" />

        <!-- lightbox starts here -->
        <link rel="stylesheet" href="{{STATIC_URL}}css/lightbox_main.css" />
        <link rel="stylesheet" href="{{STATIC_URL}}css/lightbox_custom.css" />          
        
    </head>
    
    <body>
        
        <div id="header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12" id="brand_image">
                        <img src="{{STATIC_URL}}img/logo1.jpg" class="img-responsive">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="navbar">
                        <ul>
                            <li>
                              {% url 'home' as home_url %}
                              <a href="{{home_url}}" {% if request.get_full_path == home_url %}class="active"{% endif %}>Home</a>
                            </li>
                            <li>
                              {% url 'blog' as blog_url %}
                              <a href="{{blog_url}}" {% if '/blog/' in request.path %}class="active"{% endif %}>Blog</a>
                            </li>
                            <li>
                              {% url 'illustration' as illustration_url %}
                              <a href="{{illustration_url}}" {% if '/illustration/' in request.path %}class="active"{% endif %}>Illustration</a>
                            </li>
                            <li>
                              {% url 'inspiration' as inspiration_url %}
                              <a href="{{inspiration_url}}" {% if '/inspiration/' in request.path %}class="active"{% endif %}>Inpiration</a>
                            </li>
                            <li>
                              {% url 'fashion' as fashion_url %}
                              <a href="{{fashion_url}}" {% if '/fashion/' in request.path %}class="active"{% endif %}>Fashion</a>
                            </li>
                            <li>
                              {% url 'snaps' as snaps_url %}
                              <a href="{{snaps_url}}" {% if '/snaps/' in request.path %}class="active"{% endif %}>Snaps</a>
                            </li>
                            <li>
                              {% url 'about' as about_url %}
                              <a href="{{about_url}}" {% if request.get_full_path == about_url %}class="active"{% endif %}>About</a>
                            </li>
                            <span class="clear_both"></span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="main_content">
            {% block main_content %}

            {% endblock %}
        </div>
        
        <br>
        <br>
        
    <footer class="footer">
      <div class="container">
          <hr>
          <div class="row">
              <div id="contact">
                  <p><a href="#contact">Contact</a></p>
                  <a href="#" class="facebook"></a>
                  <a href="#" class="twitter"></a>
                  <a href="#" class="pinterest"></a>
                  <a href="#" class="googleplus"></a>
                  <a href="#" class="instagram"></a>
                  <span class="clear_both"></span>
              </div>
          </div>
          <div class="row">
              <div id="copyright_info">
              <p class="text-muted">2015 &copy; <i>Kabi Chuckles</i>. All rights reserved.</p>
              </div>
          </div>
      </div>
    </footer>

    <!-- ********* ********* JAVASCRIPT ********* ********* -->
        
      <script src="{{STATIC_URL}}js/jquery.min.js"></script>
      <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    
    
    <!-- START PARALLAX -->
      <script type="text/javascript" src="{{STATIC_URL}}js/jquery.easing.1.3.js"></script>
      <script type="text/javascript" src="{{STATIC_URL}}js/parallax.js"></script>

      <script type="text/javascript">
        $(function() {
          var $pxs_container  = $('#pxs_container');
          $pxs_container.parallaxSlider();
        });
      </script>
    <!-- END PARALLAX -->
    
        
        <!-- START OF PINTEREST -->
        
        <!-- Please call pinit.js only once per page -->
        <script type="text/javascript" async defer  data-pin-color="red" data-pin-height="28" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
        
        <!-- END   OF PINTEREST -->
        
        
        <!-- START OF FACEBOOK -->

        <!-- like -->
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <!--   share -->
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>        
        
        <!-- END OF FACEBOOK -->

        <!-- START LIGHTBOX-->
        <script src="{{STATIC_URL}}js/lightbox_custom.js"></script>
        <script src="{{STATIC_URL}}js/imagelightbox.min.js"></script>        
        <!-- end -->

    </body>
</html>

kabi_chuckles/templates/blog_detail.html
{% extends "base.html" %}
{% block main_content %}
  <div class="container">
      <hr>
      
      <div class="blog">
          <p class="blog_date"> {{blog.pubdate|date:'l'}}, {{blog.pubdate}}</p>
          <h2 class="blog_title"> {{blog.title}} </h2>
          <div class="blog_description">
            {{blog.description | safe}}
          </div>
          <div class="facebook_btn">
              <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
              <div class="fb-share-button" data-href="http://www.kisforkani.com/about/" data-layout="button_count"></div>                    
          </div>
          <p class="divider">***</p>
        
          <div class="prev_next">
            <a class="prev btn btn-info" href="#">Prev</a>
            <a class="next btn btn-info" href="#">Next</a>
            <span class="clear_both"></span>
          </div>          
        
          <div id="comments">
              <h3>Comments</h3>
          </div>
      </div>
      
  </div>
{% endblock %}

kabi_chuckles/templates/blogs.html
{% extends "base.html" %}
{% block main_content %}

  <div class="container">
      <hr>
      {% if blogs.count > 0 %}
        {% for blog in blogs.object_list %}
        <div class="blog">
            <p class="blog_date"> {{blog.pubdate|date:'l'}}, {{blog.pubdate}} </p>
            <h2 class="blog_title"> {{blog.title}} </h2>
            {% if blog.default_first_image_size %}
              <img src="{{blog.first_image}}" class="blog_img_default img-responsive img-thumbnail">
            {% else %}
              <img src="{{blog.first_image}}" class="blog_img_large img-responsive img-thumbnail">
            {% endif %}
                <a href="{{blog_url}}{{blog.pk}}" class="blog_read_more btn btn-info">Read more</a>
            <div class="container">
                <p class="divider">***</p>
            </div>
        </div>
        {% endfor %}

      {% else %}
      <div class="blog">
        <p class="blog_date">No blog written yet!</p>
      </div>
      {% endif %}

      <div class="prev_next">

        {% if blogs.has_previous %}
          <a class="prev btn btn-info" href="?page={{blogs.previous_page_number}}">Prev</a>
        {% endif %}
        {% if blogs.has_next %}
          <a class="next btn btn-info" href="?page={{blogs.next_page_number}}">Next</a>
        {% endif %}
        <div class="pages">
          <ul>
          <!-- Instead use the page_range by indexing. -->
          {% for pg in page_range %}
            {% if blogs.number == pg %}
              <li><a href="?page={{pg}}" class="btn btn-default">{{pg}}</a></li>
            {% else %}
              <li><a href="?page={{pg}}" class="btn">{{pg}}</a></li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <span class="clear_both"></span>

      </div> 

{% load disqus_tags %}
{% disqus_show_comments %}

  </div>
{% endblock %}

kabi_chuckles/templates/fashion.html
{% extends "base.html" %}
{% block main_content %}
  <div class="container">
      <hr>
      {% if fashions.count > 0 %}
        {% for fashion in fashions.object_list %}
        <div class="blog">
            <p class="blog_date"> {{fashion.pubdate|date:'l'}}, {{fashion.pubdate}} </p>
            <h2 class="blog_title"> {{fashion.title}} </h2>
            {% if blog.default_first_image_size %}
              <img src="{{fashion.first_image}}" class="blog_img_default img-responsive img-thumbnail">
            {% else %}
              <img src="{{fashion.first_image}}" class="blog_img_large img-responsive img-thumbnail">
            {% endif %}
                <a href="{{fashion_url}}{{fashion.pk}}" class="blog_read_more btn btn-info">Read more</a>
            <div class="container">
                <p class="divider">***</p>
            </div>
        </div>
        {% endfor %}
      {% else %}
      <div class="blog">
        <p class="blog_date">Coming soon!</p>
      </div>
      {% endif %}

      <div class="prev_next">

        {% if fashions.has_previous %}
          <a class="prev btn btn-info" href="?page={{fashions.previous_page_number}}">Prev</a>
        {% endif %}
        {% if fashions.has_next %}
          <a class="next btn btn-info" href="?page={{fashions.next_page_number}}">Next</a>
        {% endif %}
        <div class="pages">
          <ul>
          <!-- Instead use the page_range by indexing. -->
          {% for pg in page_range %}
            {% if fashions.number == pg %}
              <li><a href="?page={{pg}}" class="btn btn-default">{{pg}}</a></li>
            {% else %}
              <li><a href="?page={{pg}}" class="btn">{{pg}}</a></li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <span class="clear_both"></span>

      </div>

{% load disqus_tags %}
{% disqus_show_comments %}
      
  </div>
{% endblock %}

kabi_chuckles/templates/fashion_detail.html
{% extends "base.html" %}
{% block main_content %}
  <div class="container">
      <hr>
      
      <div class="blog">
          <p class="blog_date"> {{fashion.pubdate|date:'l'}}, {{fashion.pubdate}} </p>
          <h2 class="blog_title"> {{fashion.title}} </h2>
          <div class="blog_description">
            {{ fashion.description|safe}}
          </div>
          <div class="facebook_btn">
              <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
              <div class="fb-share-button" data-href="http://www.kisforkani.com/about/" data-layout="button_count"></div>                    
          </div>
              <p class="divider">***</p>
          
          <div class="prev_next">
            <a class="prev btn btn-info" href="#">Prev</a>
            <a class="next btn btn-info" href="#">Next</a>
            <span class="clear_both"></span>
          </div>          
                    
          <div id="comments">
              <h3>Comments</h3>
          </div>
      </div>
      
  </div>
{% endblock %}

kabi_chuckles/templates/illustrations.html
{% extends "base.html" %}
{% block main_content %}
  <div class="container">
      <hr>
      {% if illustrations.count > 0 %}
        {% for illustration in illustrations.object_list %}
        <div class="blog">
            <p class="blog_date"> {{illustration.pubdate|date:'l'}}, {{illustration.pubdate}} </p>
            <h2 class="blog_title"> {{illustration.title}} </h2>
            {% if blog.default_first_image_size %}
              <img src="{{illustration.first_image}}" class="blog_img_default img-responsive img-thumbnail">
            {% else %}
              <img src="{{illustration.first_image}}" class="blog_img_large img-responsive img-thumbnail">
            {% endif %}
                <a href="{{illustration_url}}{{illustration.pk}}" class="blog_read_more btn btn-info">Read more</a>
            <div class="container">
                <p class="divider">***</p>
            </div>
        </div>
        {% endfor %}
      {% else %}
      <div class="blog">
        <p class="blog_date">Coming soon!</p>
      </div>
      {% endif %}


      <div class="prev_next">

        {% if illustrations.has_previous %}
          <a class="prev btn btn-info" href="?page={{illustrations.previous_page_number}}">Prev</a>
        {% endif %}
        {% if illustrations.has_next %}
          <a class="next btn btn-info" href="?page={{illustrations.next_page_number}}">Next</a>
        {% endif %}
        <div class="pages">
          <ul>
          <!-- Instead use the page_range by indexing. -->
          {% for pg in page_range %}
            {% if illustrations.number == pg %}
              <li><a href="?page={{pg}}" class="btn btn-default">{{pg}}</a></li>
            {% else %}
              <li><a href="?page={{pg}}" class="btn">{{pg}}</a></li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <span class="clear_both"></span>

      </div>

{% load disqus_tags %}
{% disqus_show_comments %}

  </div>
{% endblock %}

kabi_chuckles/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Bootstrap</title>
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/custom.css">
        <link rel="stylesheet" href="css/font.css">
        
    </head>
    
    <body>
        
        <div id="header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12" id="brand_image">
                        <img src="img/logo1.jpg" class="img-responsive">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" id="navbar">
                        <ul>
                            <li><a href="home.html" class="active">Home</a></li>
                            <li><a href="blogs.html">Blog</a></li>
                            <li><a href="blogs.html">Illustration</a></li>
                            <li><a href="blogs.html">Inpiration</a></li>
                            <li><a href="blogs.html">Fashion</a></li>
                            <li><a href="snaps.html">Snaps</a></li>
                            <li><a href="about.html">About</a></li>
                            <span class="clear_both"></span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="main_content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12" id="carousel">
                        <img src="img/image_1.jpg" class="img-responsive"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12" id="carousel_info">
                        <p>Carousel Info</p>
                    </div>
                </div>
            </div>
        </div>
        
    <footer class="footer">
      <div class="container">
          <hr>
          <div class="row">
              <div id="contact">
                  <p><a href="#contact">Contact</a></p>
                  <a href="#" class="facebook"></a>
                  <a href="#" class="twitter"></a>
                  <a href="#" class="pinterest"></a>
                  <a href="#" class="googleplus"></a>
                  <a href="#" class="instagram"></a>
                  <span class="clear_both"></span>
              </div>
          </div>
          <div class="row">
              <div id="copyright_info"
              <p class="text-muted">2015 &copy; <i>Kabi Chuckles</i>. All rights reserved.</p>
          </div>
      </div>
    </footer>
        
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        
        <!-- START OF PINTEREST -->
        
        <!-- Please call pinit.js only once per page -->
        <script type="text/javascript" async defer  data-pin-color="red" data-pin-height="28" data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
        
        <!-- END   OF PINTEREST -->
        
        
        <!-- START OF FACEBOOK -->

        <!-- like -->
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <!--   share -->
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>        
        
        <!-- END OF FACEBOOK -->
    </body>
</html>

kabi_chuckles/templates/inspiration_detail.html
{% extends "base.html" %}
{% block main_content %}
  <div class="container">
      <hr>
      
      <div class="blog">
          <p class="blog_date"> {{inspiration.pubdate|date:'l'}}, {{inspiration.pubdate}} </p>
          <h2 class="blog_title"> {{inspiration.title}} </h2>
          <div class="blog_description">
            {{inspiration.description | safe}}
          </div>
          <div class="facebook_btn">
              <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
              <div class="fb-share-button" data-href="http://www.kisforkani.com/about/" data-layout="button_count"></div>                    
          </div>
              <p class="divider">***</p>

          <div class="prev_next">
            <a class="prev btn btn-info" href="#">Prev</a>
            <a class="next btn btn-info" href="#">Next</a>
            <span class="clear_both"></span>
          </div>                        
          
          <div id="comments">
              <h3>Comments</h3>
          </div>
      </div>
      
  </div>
{% endblock %}

kabi_chuckles/templates/snap_endless.html
{% extends "base.html" %}

{% block main_content %}
<div id="main_content">
    <div id="snap_wrapper" class="container">
        <hr>
        {% if snapgroup.count > 0 %}
            
            <div class="endless_page_template">
                {% include page_template %}
            </div>

            {% block js %}
                <script src="http://code.jquery.com/jquery-latest.js"></script> 
                <script src="{{ STATIC_URL }}endless_pagination/js/endless_on_scroll.js"></script>
                <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
                <script>
                    $.endlessPaginate({paginateOnScroll: true,
                    endless_on_scroll_margin : 10
                    });
                </script>
            {% endblock %}           

        {% else %}
            <li><p>No SNAPGROUP yet!</p></li>
            <span class="clear_both"></span>
        {% endif %}
    
    {% load disqus_tags %}
    {% disqus_show_comments %}
    
    </div>

</div>
{% endblock %}

kabi_chuckles/templates/snapgroup_endless.html
{% load endless %}

{% paginate 1 snapgroup %}

{% for sg in snapgroup %}
    <h4 id="combination" class="snap_date">{{sg.date|date:'l'}}, {{sg.date}}</h4>
    <ul>
    {% for snap in sg.snap_set.all %}
        <li><a href="{{MEDIA_URL}}{{snap.image}}" data-imagelightbox="f"><img src="{{MEDIA_URL}}{{snap.image}}" alt="{{snap.caption}}" /></a></li>
    {% endfor %}
        <span class="clear_both"></span>
    </ul>
{% endfor %}

{% show_more "more..." "working" %}

kabi_chuckles/templates/snapgroups.html
{% for sg in snapgroup.object_list %}
    <h4 id="combination" class="snap_date">{{sg.date|date:'l'}}, {{sg.date}}</h4>
    <ul>
    {% for snap in sg.snap_set.all %}
        <li><a href="{{MEDIA_URL}}{{snap.image}}" data-imagelightbox="f"><img src="{{MEDIA_URL}}{{snap.image}}" alt="{{snap.caption}}" /></a></li>
    {% endfor %}
        <span class="clear_both"></span>
    </ul>
{% endfor %}